### ISSUE TITLE
Export to excel with colspan and rowspan 

### ISSUE THREAD

**Issue by EUphorik** [kayalshri/tableExport.jquery.plugin#30]
Hello, 

I have a little disagrement with my table structure : colspans and rowspans are not 'translate' from Html to Excel causing shifts in the exported file :/

any idea to solve that ?

**Comment by EUphorik** [comment]
Hi, 
i solved my problem, here is my code . 
<pre lang="javascript"><code>
$(this).filter(':visible').find('th').each(function(index,data) {
if ($(this).css('display') != 'none'){
        if(defaults.ignoreColumn.indexOf(index) == -1){
        colSpan = ($(this).prop("colSpan") > 0) ? $(this).prop("colSpan") : 1;
        rowSpan = ($(this).prop("rowSpan") > 0) ? $(this).prop("rowSpan") : 1;
        excel += "&lt;td colSpan='"+colSpan+"' rowSpan='"+rowSpan+"'&gt;" + parseString($(this))+ "&lt;/td&gt;";
        }
    }
});
<pre></code>

**Comment by mcateja** [comment]
how to use above function
