### ISSUE TITLE
[Solved] Wrong mime type word files and filename dialog 

### ISSUE THREAD

**Issue by ghost** [kayalshri/tableExport.jquery.plugin#46]
Hi,

I was trying to export _xls_ and _doc_, but fails filename and fails extension, here is the solution :pill:

:computer: **Current line (_line 279_):**
_window.open('data:application/vnd.ms-'+defaults.type+';filename=exportData.doc;' + base64data);_

Replace the current line with:
:zap: **powerful new lines:**

```
var anchor = document.createElement('a');//Create an anchor element
document.body.appendChild(anchor); //Add it to document
anchor.href = 'data:application/vnd.ms' + (defaults.type === 'doc' ? 'word' : '-' + defaults.type) + ';filename=exportData.doc;' + base64data; //Create content and mime type
anchor.download = 'exportData.' + (defaults.type === 'excel' ? 'xls' : (defaults.type === 'powerpoint' ? 'ppt' : defaults.type)); //Custom filename+ext (ext fix)                  
anchor.click();//Launch
```

**Office MIME Types:**
- http://filext.com/faq/office_mime_types.php

:white_check_mark: Tested on: Chrome, Firefox. 
_(Sorry IE)._

:grimacing:

**Comment by facuxt** [comment]
Thank you very much!! this helped a lot!
