### ISSUE TITLE
Extra Table Being Rendered, top row not being rendered correctly

### ISSUE THREAD

**Issue by LukeBrumfield** [kayalshri/tableExport.jquery.plugin#51]
Is anyone else getting this sort of error? I don't know if this is an issue with jsPDF, jsPDF autotable, or this library. 

I have attached my table, the function call, and the restulting pdf.

<table class="pvtTable" data-numrows="3" data-numcols="4"><thead><tr><th rowspan="2" class="pvtAxisLabel">ethn</th><th class="pvtColLabel" colspan="2">no</th><th class="pvtColLabel" colspan="2">yes</th><th rowspan="2" class="pvtTotalLabel">Totals</th></tr><tr><th class="pvtColLabel" colspan="1">no</th><th class="pvtColLabel" colspan="1">yes</th><th class="pvtColLabel" colspan="1">no</th><th class="pvtColLabel" colspan="1">yes</th></tr></thead><tbody><tr><td class="pvtRowLabel" rowspan="1">black</td><td class="pvtVal row0 col0" data-value="243">243</td><td class="pvtVal row0 col1" data-value="131">131</td><td class="pvtVal row0 col2" data-value="74">74</td><td class="pvtVal row0 col3" data-value="56">56</td><td class="pvtTotal rowTotal" data-value="504" data-for="row0">504</td></tr><tr><td class="pvtRowLabel" rowspan="1">hisp</td><td class="pvtVal row1 col0" data-value="285">285</td><td class="pvtVal row1 col1" data-value="90">90</td><td class="pvtVal row1 col2" data-value="209">209</td><td class="pvtVal row1 col3" data-value="96">96</td><td class="pvtTotal rowTotal" data-value="680" data-for="row1">680</td></tr><tr><td class="pvtRowLabel" rowspan="1">other</td><td class="pvtVal row2 col0" data-value="1360">1,360</td><td class="pvtVal row2 col1" data-value="337">337</td><td class="pvtVal row2 col2" data-value="1125">1,125</td><td class="pvtVal row2 col3" data-value="354">354</td><td class="pvtTotal rowTotal" data-value="3176" data-for="row2">3,176</td></tr><tr><td class="pvtTotalLabel" colspan="1">Totals</td><td class="pvtTotal colTotal" data-value="1888" data-for="col0">1,888</td><td class="pvtTotal colTotal" data-value="558" data-for="col1">558</td><td class="pvtTotal colTotal" data-value="1408" data-for="col2">1,408</td><td class="pvtTotal colTotal" data-value="506" data-for="col3">506</td><td class="pvtGrandTotal" data-value="4360">4,360</td></tr></tbody></table>

`
  <a href="#" onclick="$('.pvtTable').tableExport(  {type: 'pdf',jspdf: {format: 'bestfit', autotable: {tableWidth: 'wrap'}}});">PDF</a>
`

[tableExport(2).pdf](https://github.com/kayalshri/tableExport.jquery.plugin/files/138514/tableExport.2.pdf)

**Comment by hhurz** [comment]
FYI: that issue seems to refer to my [fork](https://github.com/hhurz/tableExport.jquery.plugin) of this plugin. Feel free to open an issue there. Actually jsPDF autotable handles only a single header row of a table. Thus this limitation leads to the problem you have reported.

**Comment by Grendizr** [comment]
I opened [an issue on their side](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/161) for that purpose
