### ISSUE TITLE
How to determine download file name ?

### ISSUE THREAD

**Issue by leo-def** [kayalshri/tableExport.jquery.plugin#79]
I need download the file in a different name, this tool accept fileName parameter ?

**Comment by jackmatt2** [comment]
me too

**Comment by mbj2014** [comment]
It is use window.open() function to export excel file with HTML.

**Comment by madzman23** [comment]
Did you guys manage to changed the filename of the export file? Thanks.

**Comment by ActingCute** [comment]
too yes
